DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

COMMENT ON TABLE users IS 'user information';
COMMENT ON COLUMN users.id IS 'user id';
COMMENT ON COLUMN users.name IS 'user name';
COMMENT ON COLUMN users.created_at IS 'created time'
COMMENT ON COLUMN users.updated_at IS 'updated time'

DROP TABLE IF EXISTS notes CASCADE;
CREATE TABLE IF NOT EXISTS notes (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
);

COMMENT ON TABLE notes IS 'note information';
COMMENT ON COLUMN notes.id IS 'note id';
COMMENT ON COLUMN notes.name IS 'note name';
COMMENT ON COLUMN notes.user_id IS 'author id';
COMMENT ON COLUMN notes.created_at IS 'created time';
COMMENT ON COLUMN notes.updated_at IS 'updated time';

DROP TABLE IF EXISTS transcriptions CASCADE;
CREATE TABLE IF NOT EXISTS transcriptions (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note_id BIGINT,
    PRIMARY KEY(id),
    FOREIGN KEY(note_id) REFERENCES notes(id) ON DELETE CASCADE
);

COMMENT ON TABLE transcriptions IS 'transcriptions in a note';
COMMENT ON COLUMN transcriptions.id IS 'transcription id';
COMMENT ON COLUMN transcriptions.content IS 'transcription content';
COMMENT ON COLUMN transcriptions.created_at IS 'transcription created_at';
COMMENT ON COLUMN transcriptions.updated_at IS 'transcription updated_at';
COMMENT ON COLUMN transcriptions.note_id IS 'transcription note_id';